# Generated by Django 4.1.3 on 2022-12-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podruznica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjesto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Polica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(max_length=50)),
                ('trajanje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Klijent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=20)),
                ('prezime', models.CharField(max_length=20)),
                ('datum_rodenja', models.DateField()),
                ('datum_sklapanja', models.DateField()),
                ('podruznica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.podruznica')),
                ('polica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.polica')),
            ],
        ),
    ]
