# Generated by Django 4.1.3 on 2022-12-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klijent',
            name='datum_sklapanja',
        ),
        migrations.RemoveField(
            model_name='klijent',
            name='polica',
        ),
        migrations.CreateModel(
            name='Ugovor',
            fields=[
                ('osiguranje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.polica')),
                ('datum_sklapanja', models.DateField()),
                ('clan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.klijent')),
            ],
        ),
        migrations.AddField(
            model_name='klijent',
            name='polica',
            field=models.ManyToManyField(to='main.polica'),
        ),
    ]
