# Generated by Django 4.1.3 on 2022-12-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_klijent_datum_sklapanja_remove_klijent_polica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klijent',
            name='polica',
        ),
        migrations.AddField(
            model_name='klijent',
            name='polica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.polica'),
        ),
    ]
