# Generated by Django 4.1.3 on 2022-12-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_klijent_polica_klijent_polica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ugovor',
        ),
    ]
